# Generated by Django 2.2.5 on 2019-09-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('guapaijia', models.IntegerField(db_column='d_guapaijia', verbose_name='挂牌价')),
                ('chengjiaozhouqi', models.IntegerField(db_column='d_chengjiaozhouqi', verbose_name='成交周期')),
                ('tiaojia', models.IntegerField(db_column='d_tiaojia', verbose_name='调价')),
                ('daikan', models.IntegerField(db_column='d_daikan', verbose_name='带看')),
                ('guanzhu', models.IntegerField(db_column='d_guanzhu', verbose_name='关注')),
                ('liulan', models.IntegerField(db_column='d_liulan', verbose_name='浏览')),
                ('fangwuhuxing', models.CharField(db_column='d_fangwuhuxing', max_length=20, verbose_name='房屋户型')),
                ('suozailouceng', models.CharField(db_column='d_suozailouceng', max_length=20, verbose_name='所在楼层')),
                ('jianzhumianji', models.IntegerField(db_column='d_jianzhumianji', verbose_name='建筑面积')),
                ('huxingjiegou', models.CharField(db_column='d_huxingjiegou', max_length=20, verbose_name='户型结构')),
                ('taoneimianji', models.CharField(db_column='d_taoneimianji', max_length=20, verbose_name='套内面积')),
                ('jianzhuleixing', models.CharField(db_column='d_jianzhuleixing', max_length=20, verbose_name='建筑类型')),
                ('fangwuchaoxiang', models.CharField(db_column='d_fangwuchaoxiang', max_length=20, verbose_name='房屋朝向')),
                ('jianchengniandai', models.CharField(db_column='d_jianchengniandai', max_length=20, verbose_name='建成年代')),
                ('zhuangxiuqingkuang', models.CharField(db_column='d_zhuangxiuqingkuang', max_length=20, verbose_name='装修情况')),
                ('jianzhujiegou', models.CharField(db_column='d_jianzhujiegou', max_length=20, verbose_name='建筑结构')),
                ('gongnuanfangshi', models.CharField(db_column='d_gongnuanfangshi', max_length=20, verbose_name='供暖方式')),
                ('tihubili', models.CharField(db_column='d_tihubili', max_length=20, verbose_name='梯户比例')),
                ('chanquannianxian', models.CharField(db_column='d_chanquannianxian', max_length=20, verbose_name='产权年限')),
                ('peibeidianti', models.CharField(db_column='d_peibeidianti', max_length=20, verbose_name='配备电梯')),
                ('lianjiabianhao', models.BigIntegerField(db_column='d_lianjiabianhao', primary_key=True, serialize=False, verbose_name='链家编号')),
                ('jiaoyiquanshu', models.CharField(db_column='d_jiaoyiquanshu', max_length=20, verbose_name='交易权属')),
                ('guapaishijian', models.DateField(db_column='d_guapaishijian', verbose_name='挂牌时间')),
                ('fangwuyongtu', models.CharField(db_column='d_fangwuyongtu', max_length=20, verbose_name='房屋用途')),
                ('fangwunianxian', models.IntegerField(db_column='d_fangwunianxian', verbose_name='房屋年限')),
                ('fangquansuoshu', models.CharField(db_column='d_fangquansuoshu', max_length=20, verbose_name='房权所属')),
                ('chengjiaojia', models.IntegerField(db_column='d_chengjiaojia', verbose_name='成交价')),
                ('danjia', models.IntegerField(db_column='d_danjia', verbose_name='单价')),
                ('xiaoquweizhi', models.IntegerField(db_column='d_xiaoquweizhi', verbose_name='小区位置')),
                ('chengjaoriqi', models.DateField(db_column='d_chengjaoriqi', verbose_name='成交日期')),
            ],
            options={
                'db_table': 'tb_house',
            },
        ),
    ]
