# Generated by Django 2.2.5 on 2019-09-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_prices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='fangwunianxian',
            field=models.CharField(db_column='d_fangwunianxian', max_length=20, verbose_name='房屋年限'),
        ),
    ]
