# Generated by Django 2.2.5 on 2020-02-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_prices', '0004_auto_20200217_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondHandHouse',
            fields=[
                ('location', models.CharField(db_column='d_location', max_length=20, verbose_name='位置')),
                ('total_price', models.IntegerField(db_column='d_total_price', verbose_name='总价')),
                ('space', models.IntegerField(db_column='d_space', verbose_name='面积')),
                ('single_price', models.IntegerField(db_column='d_single_price', verbose_name='单价')),
                ('house_type', models.CharField(db_column='d_house_type', max_length=20, verbose_name='户型')),
                ('direction', models.CharField(db_column='d_direction', max_length=20, verbose_name='朝向')),
                ('open_date', models.DateField(db_column='d_open_date', verbose_name='挂牌日期')),
                ('source_link', models.CharField(db_column='d_source_link', max_length=100, verbose_name='房源链接')),
                ('lianjia_number', models.BigIntegerField(db_column='d_lianjia_number', primary_key=True, serialize=False, verbose_name='链家编号')),
            ],
            options={
                'db_table': 'tb_second_hand_house',
            },
        ),
        migrations.CreateModel(
            name='SoldHouse',
            fields=[
                ('location', models.CharField(db_column='d_location', max_length=20, verbose_name='位置')),
                ('total_price', models.IntegerField(db_column='d_total_price', verbose_name='总价')),
                ('space', models.IntegerField(db_column='d_space', verbose_name='面积')),
                ('single_price', models.IntegerField(db_column='d_single_price', verbose_name='单价')),
                ('house_type', models.CharField(db_column='d_house_type', max_length=20, verbose_name='户型')),
                ('direction', models.CharField(db_column='d_direction', max_length=20, verbose_name='朝向')),
                ('open_date', models.DateField(db_column='d_open_date', verbose_name='挂牌日期')),
                ('sold_date', models.DateField(db_column='d_sold_date', verbose_name='成交日期')),
                ('source_link', models.CharField(db_column='d_source_link', max_length=100, verbose_name='房源链接')),
                ('lianjia_number', models.BigIntegerField(db_column='d_lianjia_number', primary_key=True, serialize=False, verbose_name='链家编号')),
            ],
            options={
                'db_table': 'tb_sold_house',
            },
        ),
    ]
